# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotGeometryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(934, 484)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 20, 911, 451))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(610, 70, 281, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widgetGeometryWindowText = QtWidgets.QWidget(self.frame_2)
        self.widgetGeometryWindowText.setGeometry(QtCore.QRect(10, 10, 261, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetGeometryWindowText.setFont(font)
        self.widgetGeometryWindowText.setObjectName("widgetGeometryWindowText")
        self.label_4 = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LabeldettypeGeo = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.LabeldettypeGeo.setGeometry(QtCore.QRect(130, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.LabeldettypeGeo.setFont(font)
        self.LabeldettypeGeo.setObjectName("LabeldettypeGeo")
        self.label_6 = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.LabeldetmatGeo = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.LabeldetmatGeo.setGeometry(QtCore.QRect(130, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.LabeldetmatGeo.setFont(font)
        self.LabeldetmatGeo.setObjectName("LabeldetmatGeo")
        self.label_8 = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.label_8.setGeometry(QtCore.QRect(30, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.LabelmtempGeo = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.LabelmtempGeo.setGeometry(QtCore.QRect(140, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.LabelmtempGeo.setFont(font)
        self.LabelmtempGeo.setObjectName("LabelmtempGeo")
        self.label_10 = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.label_10.setGeometry(QtCore.QRect(30, 110, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.labelGeoNumberWires = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.labelGeoNumberWires.setGeometry(QtCore.QRect(180, 110, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.labelGeoNumberWires.setFont(font)
        self.labelGeoNumberWires.setObjectName("labelGeoNumberWires")
        self.label_13 = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.label_13.setGeometry(QtCore.QRect(30, 170, 311, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.label_11.setGeometry(QtCore.QRect(30, 140, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.labelGeoMplane = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.labelGeoMplane.setGeometry(QtCore.QRect(180, 140, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.labelGeoMplane.setFont(font)
        self.labelGeoMplane.setObjectName("labelGeoMplane")
        self.labelGeoBtype = QtWidgets.QLabel(self.widgetGeometryWindowText)
        self.labelGeoBtype.setGeometry(QtCore.QRect(120, 170, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.labelGeoBtype.setFont(font)
        self.labelGeoBtype.setObjectName("labelGeoBtype")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(660, 60, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widgetGeometryPlot = QtWidgets.QWidget(self.frame)
        self.widgetGeometryPlot.setGeometry(QtCore.QRect(10, 10, 571, 431))
        self.widgetGeometryPlot.setObjectName("widgetGeometryPlot")
        self.pushButtonGeoPlot = QtWidgets.QPushButton(self.frame)
        self.pushButtonGeoPlot.setGeometry(QtCore.QRect(680, 340, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.pushButtonGeoPlot.setFont(font)
        self.pushButtonGeoPlot.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonGeoPlot.setObjectName("pushButtonGeoPlot")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Detector: "))
        self.LabeldettypeGeo.setText(_translate("Form", "dettype"))
        self.label_6.setText(_translate("Form", "Material:"))
        self.LabeldetmatGeo.setText(_translate("Form", "detmat"))
        self.label_8.setText(_translate("Form", "Melting Temp:"))
        self.LabelmtempGeo.setText(_translate("Form", "mtemp"))
        self.label_10.setText(_translate("Form", "Number of Wires:"))
        self.labelGeoNumberWires.setText(_translate("Form", "maxtemp"))
        self.label_13.setText(_translate("Form", "Beam Type: "))
        self.label_11.setText(_translate("Form", "Plane of Measurement:"))
        self.labelGeoMplane.setText(_translate("Form", "maxtemp"))
        self.labelGeoBtype.setText(_translate("Form", "maxtemp"))
        self.label_2.setText(_translate("Form", "    DETECTOR PARAMETERS"))
        self.pushButtonGeoPlot.setText(_translate("Form", "Plot"))
        self.label.setText(_translate("Form", "GEOMETRY WINDOW"))
