# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotResultsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1131, 610)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(10, 70, 791, 511))
        self.frame_6.setStyleSheet("background-color: rgb(240, 240, 240)\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidgetTempCp = QtWidgets.QTabWidget(self.frame_6)
        self.tabWidgetTempCp.setMinimumSize(QtCore.QSize(0, 17))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.tabWidgetTempCp.setFont(font)
        self.tabWidgetTempCp.setAutoFillBackground(False)
        self.tabWidgetTempCp.setStyleSheet("QTabBar::tab \n"
"{\n"
"    border-top-color: rgb(61, 61, 61);\n"
"    border-color: rgb(61, 61, 61);\n"
"    color: white;\n"
"    background: rgb(61, 61, 61);\n"
"}\n"
"QTabBar::tab:selected, \n"
"QTabBar::tab:hover \n"
"{\n"
"    background: white;\n"
"    color: rgb(0, 0, 0);   \n"
"    border-color:  rgb(61, 61, 61);\n"
"\n"
"}\n"
"    background-color: rgb(255, 255, 255);")
        self.tabWidgetTempCp.setIconSize(QtCore.QSize(20, 30))
        self.tabWidgetTempCp.setObjectName("tabWidgetTempCp")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widgetMaxTempVStime = QtWidgets.QWidget(self.tab)
        self.widgetMaxTempVStime.setGeometry(QtCore.QRect(-10, -10, 791, 481))
        self.widgetMaxTempVStime.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetMaxTempVStime.setObjectName("widgetMaxTempVStime")
        self.tabWidgetTempCp.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widgetMaxIntVsTime = QtWidgets.QWidget(self.tab_2)
        self.widgetMaxIntVsTime.setGeometry(QtCore.QRect(-10, -10, 781, 471))
        self.widgetMaxIntVsTime.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetMaxIntVsTime.setObjectName("widgetMaxIntVsTime")
        self.tabWidgetTempCp.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widgetFanczTemp = QtWidgets.QWidget(self.tab_3)
        self.widgetFanczTemp.setGeometry(QtCore.QRect(-10, -10, 781, 481))
        self.widgetFanczTemp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widgetFanczTemp.setObjectName("widgetFanczTemp")
        self.tabWidgetTempCp.addTab(self.tab_3, "")
        self.verticalLayout_12.addWidget(self.tabWidgetTempCp)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1121, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("font: 16pt \"Courier New\" bold;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 129, 90)")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(820, 540, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOutputSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOutputSave.sizePolicy().hasHeightForWidth())
        self.pushButtonOutputSave.setSizePolicy(sizePolicy)
        self.pushButtonOutputSave.setMaximumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonOutputSave.setFont(font)
        self.pushButtonOutputSave.setStyleSheet("background-color: rgb(61, 61, 61);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Courier New\";")
        self.pushButtonOutputSave.setObjectName("pushButtonOutputSave")
        self.horizontalLayout.addWidget(self.pushButtonOutputSave)
        self.pushButtonOutputHelp = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOutputHelp.sizePolicy().hasHeightForWidth())
        self.pushButtonOutputHelp.setSizePolicy(sizePolicy)
        self.pushButtonOutputHelp.setMaximumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonOutputHelp.setFont(font)
        self.pushButtonOutputHelp.setStyleSheet("background-color: rgb(255, 129, 90);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Courier New\";")
        self.pushButtonOutputHelp.setObjectName("pushButtonOutputHelp")
        self.horizontalLayout.addWidget(self.pushButtonOutputHelp)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(820, 450, 301, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 12pt \"Courier New\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditOutputFolderName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditOutputFolderName.setFont(font)
        self.lineEditOutputFolderName.setStyleSheet("font: 12pt \"Courier New\";")
        self.lineEditOutputFolderName.setObjectName("lineEditOutputFolderName")
        self.verticalLayout.addWidget(self.lineEditOutputFolderName)
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(820, 70, 301, 371))
        self.frame_7.setStyleSheet("background-color: rgb(240, 240, 240)\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 12pt \"Courier New\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.Labeldettype = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Labeldettype.setFont(font)
        self.Labeldettype.setStyleSheet("font: 12pt \"Courier New\";")
        self.Labeldettype.setObjectName("Labeldettype")
        self.horizontalLayout_2.addWidget(self.Labeldettype)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: 12pt \"Courier New\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.Labelmtemp = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Labelmtemp.setFont(font)
        self.Labelmtemp.setStyleSheet("font: 12pt \"Courier New\";")
        self.Labelmtemp.setObjectName("Labelmtemp")
        self.horizontalLayout_3.addWidget(self.Labelmtemp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: 12pt \"Courier New\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.Labeldetmat = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Labeldetmat.setFont(font)
        self.Labeldetmat.setStyleSheet("font: 12pt \"Courier New\";")
        self.Labeldetmat.setObjectName("Labeldetmat")
        self.horizontalLayout_4.addWidget(self.Labeldetmat)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 12pt \"Courier New\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.labelmaxtemp = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelmaxtemp.setFont(font)
        self.labelmaxtemp.setStyleSheet("font: 12pt \"Courier New\";")
        self.labelmaxtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelmaxtemp.setObjectName("labelmaxtemp")
        self.verticalLayout_2.addWidget(self.labelmaxtemp)
        self.verticalLayout_13.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.tabWidgetTempCp.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidgetTempCp.setTabText(self.tabWidgetTempCp.indexOf(self.tab), _translate("Form", "    Max. Temp    "))
        self.tabWidgetTempCp.setTabText(self.tabWidgetTempCp.indexOf(self.tab_2), _translate("Form", "   Intensity   "))
        self.tabWidgetTempCp.setTabText(self.tabWidgetTempCp.indexOf(self.tab_3), _translate("Form", "   Fancy Temp.   "))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Simulation Results</span></p></body></html>"))
        self.pushButtonOutputSave.setText(_translate("Form", "Save"))
        self.pushButtonOutputHelp.setText(_translate("Form", "Help"))
        self.label_3.setText(_translate("Form", "Output Folder Name"))
        self.lineEditOutputFolderName.setText(_translate("Form", "Output/"))
        self.label_4.setText(_translate("Form", "Detector: "))
        self.Labeldettype.setText(_translate("Form", "dettype"))
        self.label_8.setText(_translate("Form", "Melting Temp:"))
        self.Labelmtemp.setText(_translate("Form", "mtemp"))
        self.label_6.setText(_translate("Form", "Material:"))
        self.Labeldetmat.setText(_translate("Form", "detmat"))
        self.label_10.setText(_translate("Form", "Maximum Temperature:"))
        self.labelmaxtemp.setText(_translate("Form", "SIm Max temp"))
